export const cohortsConstants = {   
    GETCOHORTS_REQUEST: 'COHORTS_GETCOHORTS_REQUEST',
    GETCOHORTS_SUCCESS: 'COHORTS_GETCOHORTS_SUCCESS',
    GETCOHORTS_FAILURE: 'COHORTS_GETCOHORTS_FAILURE',
};
